// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jallokafmlyddejdpxkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphbGxva2FmbWx5ZGRlamRweGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzYzMDUsImV4cCI6MjA3MzUxMjMwNX0.3UYHA_gEztC2zgZf4TKlz65NAp1WY6HYU8Y-48yx_4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});